version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    expose:
      - 2181

  kafka:
    expose:
      - 9092
      - 8082
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    image: confluentinc/cp-kafka:3.1.1
    depends_on:
      - zookeeper

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: twashing/edgarly-app:latest
    depends_on:
      - kafka
      - zookeeper
    working_dir: ${PWD}
    ports:
      - 7888:7888
    volumes:
      - .:${PWD}
    entrypoint: lein with-profile +app run -m com.interrupt.edgarly.core/-main

  kafka-tools:
    image: confluentinc/cp-kafka:3.1.1
    tty: true
    depends_on:
      - zookeeper
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    working_dir: /usr/src/app
    entrypoint: /bin/bash
